// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clear: typeof import('./src/components/records/Clear.vue')['default']
    Create: typeof import('./src/components/mocks/Create.vue')['default']
    Delete: typeof import('./src/components/mocks/Delete.vue')['default']
    DisplayMock: typeof import("./src/components/mocks/DisplayMock.vue")["default"]
    DisplayMocks: typeof import('./src/components/mocks/DisplayMocks.vue')['default']
    Editor: typeof import('./src/components/mocks/Editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import("element-plus/es")["ElMenu"]
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Expand: typeof import('./src/components/records/Expand.vue')['default']
    ExpandedItem: typeof import('./src/components/ExpandedItem.vue')['default']
    Filter: typeof import('./src/components/records/Filter.vue')['default']
    ItemsTable: typeof import("./src/components/records/ItemsTable.vue")["default"]
    Menu: typeof import("./src/components/Menu.vue")["default"]
    Method: typeof import('./src/components/records/Method.vue')['default']
    New: typeof import('./src/components/mocks/New.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Status: typeof import('./src/components/records/Status.vue')['default']
    Table: typeof import('./src/components/mocks/Table.vue')['default']
    Timestamp: typeof import('./src/components/records/Timestamp.vue')['default']
    Update: typeof import('./src/components/mocks/Update.vue')['default']
  }
}
