- name: Get Products
  request:
    path: '/api/2022-07/graphql.json'
    method: POST
    body:
      query: '.*query getAllProducts.*'
  response:
    status: 200
    headers:
      content-type: json/template
    body: |
      {
        "data": {
          "products": {
            "pageInfo": {
              "hasNextPage": true,
              "hasPreviousPage": false
            },
            "edges": [
              {{#repeat 50}}
                {
                  "node": {
                    "id": "{{data.random.alphaNumeric 10}}",
                    "title": "{{data.commerce.productName}}",
                    "handle": "{{data.commerce.productAdjective}}",
                    "vendor": "{{data.company.name}}",
                    "availableForSale": true,
                    "isGiftCard": true,
                    "description": "{{data.commerce.productDescription "\n"}}",
                    "featuredImage": {
                       "url": "{{data.image.dataUri 517 600}}",
                        "altText": null,
                        "width": 517,
                        "height": 600
                    },
                    "tags": [
                      {{#repeat 3}}
                        "{{data.random.word}}"
                      {{/repeat}}
                    ],
                    "priceRange": {
                      "maxVariantPrice": {
                        "amount": "{{data.commerce.price}}",
                        "currencyCode": "USD"
                      },
                      "minVariantPrice": {
                        "amount": "{{data.commerce.price}}",
                        "currencyCode": "USD"
                      }
                    },
                    "images": {
                      "pageInfo": {
                        "hasNextPage": true,
                        "hasPreviousPage": false
                      },
                      "edges": [
                        {
                          "node": {
                            "url": "{{data.image.dataUri 517 600}}",
                            "altText": null,
                            "width": 517,
                            "height": 600
                          }
                        }
                      ]
                    }
                  }
                }
              {{/repeat}}
            ]
          }
        }
      }
