name: Deno Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Deno
      run: |
        export DENO_INSTALL="$HOME/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
        curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.30.0

    - name: Run tests
      working-directory: server
      run: |
        deno test
